CarsRental/CarsRental/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myCarsApp.urls")),
]

CarsRental/CarsRental_App/urls.py
from . import views
from django.urls import path

app_name = "CarsRental_App"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path("about/", views.about_view, name="about_view"),
    path("password/generate/", views.pwGenerator_view, name="pwGenerator_view")
]

CarsRental/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('', views.welcome_view, name='welcome_view'),
    path('about/', views.about_view, name='about_view'),
    path('password/generate/', views.generate_password, name='generate_password'),

]

CarsRental/main/urls.py
from django.urls import path
from . import views
app_name="main"
urlpatterns = [
    path('', views.welcome_page,name='welcome_page'),
    path('about/', views.about_page,  name='about_page'),
    path('password/generate/', views.password_page,name='password_page')

]

CarsRental/CarsRental_App/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
import random
import string
import datetime

def home_view(request : HttpRequest):

    return render(request, "main/home.html")

def about_view(request: HttpRequest):

    return render(request, "main/about.html")

def about_view(request: HttpRequest):
    date = datetime.datetime.now()
    return render(request, "main/about.html" , context ={"date_time":date})

def pwGenerator_view(request:HttpRequest):
    length = 10
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(length))

    return render(request, "main/passwordGenerator.html", context={"password": password})

CarsRental/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
import string , random 

def welcome_view(request:HttpResponse):

    return render(request,"home/welcome.html")


def about_view(request:HttpResponse):

    return render(request,"home/about.html")

def generate_password(request:HttpResponse):

    symbols = '@$*()_-+={[}]|:;,.?'
    chars = string.ascii_letters +symbols+ string.digits
    password = ''.join(random.choice(chars) for i in range(10))

    return render(request,"home/password.html",context={"password":password})

# Create your views here.

CarsRental/main/views.py
from django.shortcuts import render
from django.http import HttpRequest , HttpResponse
import string , random

# Create your views here.
def welcome_page(request:HttpResponse):
    welcome="Hello World, This is my new HOME for Car Rentals Website  ! we're excited to welcome you here."
    today_date="2024/7/7"
    return render(request ,'main/welcome.html',context={'welcome':welcome ,"today_date":today_date})

def about_page(request:HttpResponse):
    about= '''A simple paragraph about Car Rentals.
    -car rental is a service that is beneficial for providing vehicles to people on rent for a short period. It is the hiring of vehicles from one party to another.
       Rents are based on the time you need the vehicles for some hours, daily, weekly and monthly.
    '''
    return render(request ,'main/about.html',context={'about':about})


def password_page(request:HttpResponse):
    symbols="!@#$%^&*()_-+=[]{}|;:,.<>?/"
    characters = string.ascii_letters +symbols+ string.digits
    password = ''.join(random.choice(characters) for i in range(10))
    return render(request ,'main/password_generator.html',context={"password_generator":password})


# def home(request):
#     return render(request,"main/base.html")

# def about(request):
#     return render(request, 'about.html')

# def password_generator(request):
#     return render(request, 'password_generator.html')

CarsRental/CarsRental_App/templates/main/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>About us</title>
  </head>
  <body>
    <header>
      <h1>Welcome to My Webpage</h1>
      <nav>
        <ul>
          <li><a href="{% url 'CarsRental_App:home_view' %}">Home</a></li>
          <li><a href="{% url 'CarsRental_App:about_view' %}">About</a></li>
          <li>
            <a href="{% url 'CarsRental_App:pwGenerator_view' %}"
              >Password Generator</a
            >
          </li>
        </ul>
      </nav>
    </header>
    <main>
      <section>
        <h2>About us</h2>
        <p>This is the about us section of the webpage.</p>
        <img src="/static/images/image.jpeg"/>
        <img src="{% static 'images/image.jpeg' %}"/>
        <p>Today Date is {{date_time}}.</p>
      </section>
    </main>
    <footer><p>&copy; 2024 My Webpage. All rights reserved.</p></footer>
  </body>
</html>

CarsRental/CarsRental_App/templates/main/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<header> <nav>
        <ul>
          <li><a href="{% url 'CarsRental_App:home_view' %}">Home</a></li>
          <li><a href="{% url 'CarsRental_App:about_view' %}">About</a></li>
          <li><a href="{% url 'CarsRental_App:pwGenerator_view' %}">Password Generator</a></li>
        </ul>
      </nav>
    </header>
<body>
    <h1>Hello World, This is my new HOME for Car Rentals Website  ! we're excited to welcome you here.</h1>
</body>
</html>

CarsRental/CarsRental_App/templates/main/passwordGenerator.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Password Generator</title>
  </head>
  <body>
    <header>
      <h1>Welcome to My Webpage</h1>
      <nav>
        <ul>
          <li><a href="{% url 'CarsRental_App:home_view' %}">Home</a></li>
          <li><a href="{% url 'CarsRental_App:about_view' %}">About</a></li>
          <li>
            <a href="{% url 'CarsRental_App:pwGenerator_view' %}"
              >Password Generator</a
            >
          </li>
        </ul>
      </nav>
    </header>
    <main>
      <section>
        <h2>Password Generator</h2>

        <p>Generated password {{password}}.</p>
      </section>
    </main>
    <footer><p>&copy; 2024 My Webpage. All rights reserved.</p></footer>
  </body>
</html>