CarsRental/CarsRental/CarsRental/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Cars.urls')),

]

CarsRental/CarsRental/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myCarsApp.urls")),
]

CarsRental/home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('', views.welcome_view, name='welcome_view'),
    path('about/', views.about_view, name='about_view'),
    path('password/generate/', views.generate_password, name='generate_password'),

]

CarsRental/main/urls.py
from django.urls import path
from . import views
app_name="main"
urlpatterns = [
    path('', views.welcome_page,name='welcome_page'),
    path('about/', views.about_page,  name='about_page'),
    path('password/generate/', views.password_page,name='password_page')

]

CarsRental/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
import string , random 

def welcome_view(request:HttpResponse):

    return render(request,"home/welcome.html")


def about_view(request:HttpResponse):

    return render(request,"home/about.html")

def generate_password(request:HttpResponse):

    symbols = '@$*()_-+={[}]|:;,.?'
    chars = string.ascii_letters +symbols+ string.digits
    password = ''.join(random.choice(chars) for i in range(10))

    return render(request,"home/password.html",context={"password":password})

# Create your views here.

CarsRental/main/views.py
from django.shortcuts import render
from django.http import HttpRequest , HttpResponse
import string , random

# Create your views here.
def welcome_page(request:HttpResponse):
    welcome="Hello World, This is my new HOME for Car Rentals Website  ! we're excited to welcome you here."
    today_date="2024/7/7"
    return render(request ,'main/welcome.html',context={'welcome':welcome ,"today_date":today_date})

def about_page(request:HttpResponse):
    about= '''A simple paragraph about Car Rentals.
    -car rental is a service that is beneficial for providing vehicles to people on rent for a short period. It is the hiring of vehicles from one party to another.
       Rents are based on the time you need the vehicles for some hours, daily, weekly and monthly.
    '''
    return render(request ,'main/about.html',context={'about':about})


def password_page(request:HttpResponse):
    symbols="!@#$%^&*()_-+=[]{}|;:,.<>?/"
    characters = string.ascii_letters +symbols+ string.digits
    password = ''.join(random.choice(characters) for i in range(10))
    return render(request ,'main/password_generator.html',context={"password_generator":password})


# def home(request):
#     return render(request,"main/base.html")

# def about(request):
#     return render(request, 'about.html')

# def password_generator(request):
#     return render(request, 'password_generator.html')

CarsRental/main/templates/main/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About us</title>
</head>
<body>
    
    <center><b>  simple paragraph about Car Rentals. </b></center>
    <br/>
    <center> <img src="{% static 'py.png' %}" /> </center>


</body>
</html>

CarsRental/main/templates/main/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home</title>
</head>
<body>
    <img src="{% static 'images/Car.jpg' %}" alt="An image of a car rental sign">
    <h1>Hello World, This is my new HOME for Car Rentals Website! We're excited to welcome you here.</h1>
    <a href="{% url 'main:about_view' %}">About</a>
    <a href="{% url 'main:generate_password_view' %}">Password Generate</a>
</body>
</html>

CarsRental/main/templates/main/pass_generator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>passGen</title>
</head>
<body>

    <center> {{ pass_generator }} </center>
    
</body>
</html>

CarsRental/main/templates/main/password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password</title>
</head>
<body>

    <h1> your generated password is </h1>
    {{ password }}
    <br />

    <a href="{% url 'main:home' %}">back to home bage</a>

</body>
</html>

CarsRental/main/templates/main/password_generate.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Password Generate</title>
</head>
<body>
    {{password}}
</body>
</html>

CarsRental/main/templates/main/password_generator.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widyh=device-width , initial-scale=1.0">
    <title>password_generate</title>
    <style>
        h1{
            text-align: center;
        }
        span{
            color:aqua;
        }
    </style>
    </head>

<body>
    <nav>
        <br/>
        <a href="{ % url 'main:password_page'%}">password_generate</a>
        <br/>
        <a href="{% url 'main:about_page'%}">about</a>
    
       <h1>{{ password }}</h1>
    </nav>

</body>
</html>

CarsRental/main/templates/main/welcome.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="widyh=device-width , initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {{today_date}}
   <h1>Welcome </h1>
   <nav>
    <br/>
    <a href="{ % url 'main:password_generate' %}">password_generate</a>
    <br/>
    <a href="{% url 'main:about_page'%}">about</a>

   <h1>{{ Welcome }}</h1>
</nav>


</body>

</html>