carsRental/carsRental/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

carsRental/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('password/generate/', views.generate_password, name='generate_password'),
]

carsRental/main/models.py
from django.db import models

# Create your models here.

carsRental/main/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
import random
import string

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def generate_password(request):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(random.choice(characters) for i in range(10))
    return render(request, 'password.html', {'password' : password})

carsRental/main/templates/about.html
{%load static%}
<!DOCTYPE html>
<html>
<head>
    <title>About Us - Car Rentals</title>
</head>
<body>
    <h1>About Car Rentals</h1>
    <p>A simple paragraph about Car Rentals.</p>
    <img src="{% static 'images/car.jpeg' %}" alt="Car Image">
    <nav>
        <a href="{% url 'main:home' %}">Home</a> | 
        <a href="{% url 'main:generate_password' %}">Generate Password</a>
    </nav>
</body>
</html>

carsRental/main/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Home - Car Rentals</title>
</head>
<body>
    <h1>Hello World, This is my new HOME for Car Rentals Website! We're excited to welcome you here.</h1>
    <nav>
        <a href="{% url 'main:about' %}">About Us</a> | 
        <a href="{% url 'main:generate_password' %}">Generate Password</a>
    </nav>
</body>
</html>

carsRental/main/templates/password.html
<!DOCTYPE html>
<html>
<head>
    <title>Generate Password - Car Rentals</title>
</head>
<body>
    <h1>Generated Password</h1>
    <p>{{ password }}</p>
    <nav>
        <a href="{% url 'main:home' %}">Home</a> | 
        <a href="{% url 'main:about' %}">About Us</a>
    </nav>
</body>
</html>